---
apiVersion: v1
kind: Service
metadata:
    name: kafka
    namespace: kafka
    labels:
        app: kafka-service
spec:
    ports:
        - port: 9092
          name: kafka 
          protocol: TCP 
        - port: 9999
          name: jmx
          protocol: TCP
    clusterIP: None #Required for HeadlessService (no lb between pods)
    selector:
        app: kafka

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: kafka
    namespace: kafka
spec:
    selector:
        matchLabels:
            app: kafka
    serviceName: "kafka"
    replicas: 3
    podManagementPolicy: OrderedReady
    template:
        metadata:
            labels:
                app: kafka
        spec:
            containers:
            - name: kafka
              image: wurstmeister/kafka:2.12-2.5.0
              imagePullPolicy: IfNotPresent
              ports:
              - name: kafka
                containerPort: 9092
              - name: jmx
                containerPort: 9999
              env:
                - name: KAFKA_ADVERTISED_PORT 
                  value: "9092"
                - name: BROKER_ID_COMMAND
                  value: "hostname | cut -d'-' -f2"
                - name: KAFKA_ZOOKEEPER_CONNECT
                  value: "zk-cs.kafka:2181"
                - name: KAFKA_LISTENERS
                  value: "PLAINTEXT://:9092"
                - name: KAFKA_JMX_OPTS
                  value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Djava.rmi.server.hostname=127.0.0.1"
                - name: JMX_PORT
                  value: "9999"


